mysite/ankiety/urls.py
from django.urls import path

from . import views

app_name = 'ankiety'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('ankiety/', include('ankiety.urls')),
    path('admin/', admin.site.urls),
]

mysite/ankiety/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('data publikacji')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Opublikowane ostatnio?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

mysite/ankiety/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.shortcuts import redirect

from .models import Question, Choice

class IndexView(generic.ListView):
    template_name = 'ankiety/index.html'
    context_object_name = 'latest_question_list'
    def get_queryset(self):
        """Zwroc piec ostatnich opublikowanych ankiet(nie uwzgledniajac tych,
         ktore maja byc opublikowane w przyszlosci)."""
        return Question.objects.filter(
            pub_date__lte=timezone.now()
            ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'ankiety/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'ankiety/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        #wyswietl ponownie formularz do glosowania
        return render(request, 'ankiety/detail.html', {
            'question': question,
            'error_message': "Nie dokonales wyboru",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('ankiety:results', args=(question.id,)))

mysite/ankiety/templates/ankiety/base.html
{% load static %}
<html>
    <head>
        <title>Django Ankiety</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'ankiety/style.css' %}">
    </head>
    <body>
        <div class="page-header">
            <h1><a class="demoFont" href="/ankiety">Django Ankiety</a></h1>
        </div>
        <nav class="navbar navbar-expand-lg navbar-dark info-color">
            <a class="navbar-brand" href="{% url 'ankiety:index' %}">Ankiety</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                       <a class="nav-link waves-effect waves-light" href="{% url 'ankiety:index' %}">Strona główna <span class="sr-only">(current)</span></a>
                    </li>

                </ul>
            </div>
        </nav>
        <div class="box container h-50">
          <div class="row h-100 justify-content-center align-items-center">
            <div class="col-md-6">
            {% block content %}
            {% endblock %}
            </div>
          </div>
        </div>
    </body>
    <!-- Footer -->
    <footer class="page-footer font-small teal pt-4">

      <!-- Footer Text -->
      <div class="container-fluid text-center text-md-left">

        <!-- Grid row -->
        <div class="row">

          <!-- Grid column -->
          <div class="col-md-6 mt-md-0 mt-3">

            <!-- Content -->
            <h5 class="text-uppercase font-weight-bold">Chcesz dodawać ankiety?</h5>
            <p>Napisz do mnie na adres dabrowski94@gmail.com - na pewno się dogadamy :)</p>

          </div>
          <!-- Grid column -->

          <hr class="clearfix w-100 d-md-none pb-3">

          <!-- Grid column -->
          <div class="col-md-6 mb-md-0 mb-3">

            <!-- Content -->
            <h5 class="text-uppercase font-weight-bold">Projekt na zaliczenie</h5>
            <p>Z przedmiotu Języki deklaratywne. Napisany w Python - Django</p>
            <p>Maciej Dąbrowski</p>
          </div>
          <!-- Grid column -->

        </div>
        <!-- Grid row -->

      </div>
      <!-- Footer Text -->

      <!-- Copyright -->
      <div class="footer-copyright text-center py-3">© 2018 Copyright:
        <a href="https://mdbootstrap.com/education/bootstrap/"> MDBootstrap.com</a>
      </div>
      <!-- Copyright -->

    </footer>
    <!-- Footer -->

</html>

mysite/ankiety/templates/ankiety/detail.html
{% extends "ankiety/base.html" %}

{% load crispy_forms_tags %}
{% block content %}

  <h1>{{ question.question_text }}</h1>
  {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

  <form action="{% url 'ankiety:vote' question.id %}" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" class="btn btn-success" value="Głosuj">
  </form>
  
{% endblock %}

mysite/ankiety/templates/ankiety/index.html
{% extends "ankiety/base.html" %}


{% block content %}
<h5 class="text-uppercase font-weight-bold">Przegląd ostatnich ankiet</h5>
  {% if latest_question_list %}
    <ul class="list-group">
      {% for question in latest_question_list %}
        <li class="list-group-item"><a href="{% url 'ankiety:detail' question.id %}">{{ question.question_text }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>Brak ankiet do wyswietlenia.</p>
  {% endif %}
{% endblock %}

mysite/ankiety/templates/ankiety/results.html
{% extends "ankiety/base.html" %}


{% block content %}
  <h1>{{ question.question_text }}</h1>
    <ul>
      {% for choice in question.choice_set.all %}
          <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
      {% endfor %}
    </ul>
  <a class="btn btn-outline-primary" href="{% url 'ankiety:detail' question.id %}">Chcesz zaglosowac ponownie?</a>
{% endblock %}